### PR TITLE
Add todorivanov to docker-config

### PR DESCRIPTION
**Pull request by todor-ivanov**
In order to be able to follow the instruction in the end to end deployment procedures for the WMCore services I need to be able to upload images to the cmssw area in dockerhub. Thanks in advance!

### CODE REVIEW

**Comment by smuzaffar** [comment]
looks good @todor-ivanov . I just need one of dmwm admins ( @vkuznet @amaltaro @ericvaandering  ) to approve it

**Comment by vkuznet** [comment]
+1

**Comment by smuzaffar** [comment]
unfortunately we have hit the limit of docker hub team members and can not add more. docker hub has changed the "free team" policy and now they only allow "1" team with 3 members only. We already have two teams and each one of them has more than 3 members. So It is not possible to add more. I would suggest to create a service account e.g `cms-dmwm` and share that between dmwm team

**Comment by vkuznet** [comment]
I don't mind to use common service account, and if this would be the case we should let its credential to L2's and they can decide with whom they will share it.

**Comment by smuzaffar** [comment]
@vkuznet please see #121

**Comment by todor-ivanov** [comment]
Thank you @smuzaffar ! And sorry, for the extra complication it caused.

**Comment by todor-ivanov** [comment]
Just to confirm I am not doing anything wrong... because I still cannot upload [1]. Is it because of the exhausted number of users associated with the project, or it is because of a wrong reference to the repository from my side or something else?

[1]
```
denied: requested access to the resource is denied
The push refers to a repository [docker.io/cmssw/reqmgr2]
```

**Comment by vkuznet** [comment]
Todor, you're doing fine, as Shazad wrote in free addition of docker hub (which we use) there is limitation on number of users who may push. As we exceed this threshold and added you it cause a denial of your pushes.

**Comment by todor-ivanov** [comment]
Thanks @vkuznet !

**Pull request merged**
