### PR TITLE
Add gfal packages to user rhel7 images

### PR DESCRIPTION
**Pull request by aandvalenzuela**
Requested by @mapellidario

FYI, @smuzaffar, @belforte

### CODE REVIEW

**Comment by smuzaffar** [comment]
hold

**Comment by smuzaffar** [comment]
`cmssw/cms:rhel7` container is based on `opensciencegrid/osg-wn:3.5-el7` and these gfal2 packages are suppose to come from the base container. I see that `gfal2-util-scripts python3-gfal2-util` are already there.  `gfal2-all` is meta rpm which just installs various `gfal2-plugin-*` plugins . So what was missing in `cmssw/cms:rhel7` which triggered this change?

**Comment by belforte** [comment]
I am not sure which package is missing but currently:
```
belforte@lxplus738/~> cmssw-cc7
Singularity> gfal-copy
bash: gfal-copy: command not found
Singularity> 
```
`yum list|grep gfal` inside the container says all packages are in epel, but not installed.

in our container we use
```
yum install -y gfal2-util gfal2-all uberftp
```
`uberftp` is a convenient utility when debugging gridftp probelms, but in the new WebDav world it is not needed anymore.

**Comment by smuzaffar** [comment]
ah ok, this is not cmssw/cms container. @aandvalenzuela , changes should go in to https://github.com/cms-sw/cms-docker/blob/master/cc7/Dockerfile (cmssw/cc7 container)

**Comment by aandvalenzuela** [comment]
My bad, sorry! See https://github.com/cms-sw/cms-docker/pull/229/files

**Pull request closed without merging**
